### ISSUE TITLE
Can we have a .NET specific sample application to perform TBA?

### ISSUE THREAD

**Issue by somenathmaji** [cloudextend/contrib-netsuite-servicemgr#63]
A documentation would also help along with .NET sample application instead of the Angular app.

**Comment by SampathDilhan** [comment]
We can close this as we have added [ThreeStepAuthMVC](https://github.com/cloudextend/contrib-netsuite-servicemgr/tree/master/Samples/ThreeStepAuthMVC) under the PR #64.
